defmodule EnableWeb.Endpoint do
  use Phoenix.Endpoint, otp_app: :enable

  # The session will be stored in the cookie and signed,
  # this means its contents can be read but not tampered with.
  # Set :encryption_salt if you would also like to encrypt it.
  @session_options [
    store: :cookie,
    key: "_enable_key",
    signing_salt: "t3Y6P8Rd",
    same_site: "Lax"
  ]

  socket "/live", Phoenix.LiveView.Socket,
    websocket: [connect_info: [session: @session_options]],
    longpoll: [connect_info: [session: @session_options]]

  # Mirror viewer WebSocket — persistent connection for frame streaming.
  # timeout: :infinity keeps the socket open indefinitely (e-ink display stays connected).
  # longpoll disabled since we need real-time binary streaming, not polling.
  socket "/socket", EnableWeb.UserSocket,
    websocket: [timeout: :infinity],
    longpoll: false

  # Raw WebSocket for binary frame streaming to browser viewers.
  # This bypasses Phoenix Channels to avoid JSON encoding overhead
  # on binary frame data. The browser client at /mirror.html connects here.
  socket "/ws/mirror", EnableWeb.MirrorWs,
    websocket: [timeout: :infinity]

  # Serve at "/" the static files from "priv/static" directory.
  #
  # When code reloading is disabled (e.g., in production),
  # the `gzip` option is enabled to serve compressed
  # static files generated by running `phx.digest`.
  plug Plug.Static,
    at: "/",
    from: :enable,
    gzip: not code_reloading?,
    only: EnableWeb.static_paths(),
    raise_on_missing_only: code_reloading?

  # Code reloading can be explicitly enabled under the
  # :code_reloader configuration of your endpoint.
  if code_reloading? do
    socket "/phoenix/live_reload/socket", Phoenix.LiveReloader.Socket
    plug Phoenix.LiveReloader
    plug Phoenix.CodeReloader
  end

  plug Plug.RequestId
  plug Plug.Telemetry, event_prefix: [:phoenix, :endpoint]

  plug Plug.Parsers,
    parsers: [:urlencoded, :multipart, :json],
    pass: ["*/*"],
    json_decoder: Phoenix.json_library()

  plug Plug.MethodOverride
  plug Plug.Head
  plug Plug.Session, @session_options
  plug EnableWeb.Router
end
